#!/usr/bin/zsh

# On function call, call dmenu
SEL=$(echo "CONNECT\nSTATUS\nLOOP\nDISCONNECT" | dmenu -i -no-custom | tr -d '\n' | xargs)

[[ $SEL == "CONNECT" ]] && {
  # Pick VPN Server
  COUNTRY=$(echo $(nordvpn countries) | xargs | sed 's/ /\n/g' | tr -d ',-' | sed '/^[[:space:]]*$/d' | cat | dmenu -i -no-custom)
  [[ $COUNTRY ]] && {
    TG_CITY=$(echo $(nordvpn cities $COUNTRY) | xargs | sed 's/ /\n/g' | tr -d ',-' | sed '/^[[:space:]]*$/d' | cat | dmenu -i -no-custom)
  } || {
    echo "NordVPN failed to connect"
    exit 0 
  }
  
  # Connect or switch current VPN server
  nordvpn connect $TG_CITY
  echo "NordVPN Connected to $COUNTRY $TG_CITY"
} 

[[ $SEL == "STATUS" ]] && {
  # Check current status of connect if connected
  # Display with notify-send
  STAT=$(nordvpn status | tr -d '-')
  
  # Append Looping attribute if script is running
  [[ $(pgrep nordvpn_loop) ]] && {
    LOOP_STAT="Looping: True"
    echo "$STAT\n$LOOP_STAT"
  } || {
    LOOP_STAT=""
    echo "$STAT\n$LOOP_STAT"
  }
} 

[[ $SEL == "LOOP" ]] && {
  # Start NordVPN Loop 
  # reset every xx minutes
  
  # Runs nordvpn_loop if not already running
  [[ $(pgrep nordvpn_loop) ]] && {
    echo "NordVPN is already looping"
  } || {
    echo "Loop Started"
    
    # Run Loop script as a seperate process and exit
    (exec /home/alex/.config/qutebrowser/userscripts/nordvpn_loop)
  }
}

[[ $SEL == "DISCONNECT" ]] && {
  # Kill nordvpn_loop
  pkill nordvpn_loop

  # Disconnect user from VPN session if connected
  nordvpn disconnect
  echo "NordVPN Disconnected" | tr -d '-'
}

exit 0 
